name: pysurfline
channels:
  - conda-forge
dependencies:
  - python=3.9
#notebooks
  - ipython
  - ipykernel
#pysurfline
  - requests
  - pandas
  - matplotlib
#formatting and linting
  - black
  - flake8
  - flake8-rst-docstrings
#docs
  - sphinx==4.1.2
  - sphinx_rtd_theme
  - myst-parser
  - docutils=0.16
  - nbsphinx
#testing
  - pytest
  - pytest-cov
#pip
  - pip
  - pip:
    - sphinxemoji
