name: pysurfline
channels:
  - conda-forge
dependencies:
  - python=3.9
#notebooks
  - ipython
  - ipykernel
#pysurfline
  - requests
  - pandas
  - matplotlib
#formatting
  - black
#docs
  - sphinx
  - sphinx_rtd_theme
  - myst-parser
  - nbsphinx
#testing
  - pytest
  - pytest-cov
#pip
  - pip
  - pip:
    - sphinxemoji
