name: Deploy

on:
  push:
    branches: [ main]
  pull_request:
    branches: [ main ]

jobs:
  lint:
    name: Lint with Flake8
    uses: giocaizzi/python-dev-actions/.github/workflows/linting.yml@main
  versioning:
    name: Versioning checks
    uses: giocaizzi/python-dev-actions/.github/workflows/versioning.yml@main
  tests:
    name: Tests with Pytest
    uses: giocaizzi/python-dev-actions/.github/workflows/tests.yml@main
    needs: ['lint', 'versioning']
  documentation-prechecks:
    name: Documentation prechecks
    if: github.event_name == 'pull_request'
    uses: giocaizzi/python-dev-actions/.github/workflows/documentation_precheck.yml@main
    needs: ['lint', 'versioning']
  to-do-issues:
    name: To Do Issues
    if: github.event_name == 'push'
    uses: giocaizzi/python-dev-actions/.github/workflows/todo.yml@main
    needs: tests