name: Deploy

on:
  push:
    branches: [ main]
  pull_request:
    branches: [ main ]

jobs:
  lint:
    name: Lint with Flake8
    uses: giocaizzi/python-dev-actions/.github/workflows/linting.yml@main
  tests:
    name: Tests with Pytest
    uses: giocaizzi/python-dev-actions/.github/workflows/tests.yml@main
    needs: lint
  to-do-issues:
    name: To Do Issues
    if: github.event_name == 'push'
    uses: giocaizzi/python-dev-actions/.github/workflows/todo.yml@main
    needs: tests