name: Deploy

on:
  push:
    branches: [ main]
  pull_request:
    branches: [ main ]

jobs:
  lint:
    uses: giocaizzi/python-dev-actions/.github/workflows/linting.yml@main
  tests:
    uses: giocaizzi/python-dev-actions/.github/workflows/tests.yml@main