name: Documentation build

on:
  push:
    branches: [gh-pages]
  pull_request:
    branches: [gh-pages]

jobs:
  docs:
    uses: giocaizzi/python-dev-actions/.github/workflows/documentation.yml@main
