name: Documentation

on:
  push:
    branches:
      - gh-pages

jobs:
  docs:
    runs-on: ubuntu-latest
    steps:

    - uses: actions/checkout@v3
      with:
        ref : gh-pages

    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: "3.9"

    - name: Set up dependencies
      run: |
        sudo apt install pandoc
        pip install --upgrade pip 
        pip install -r requirements.txt
        pip install -r docsrc/requirements.txt
        pip install -e . 
  
    - name: Building docs
      run : |
        cd docsrc/
        make github-action
        cd ..

    - name: Commit documentation changes
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add .
        git commit -m "Actions: Build documentation" -a || true
    
      # The last command will fail if no changes were present, so we ignore
      # the return code.

    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        branch: gh-pages
        github_token: ${{ secrets.GITHUB_TOKEN }}