name: Flake8 Linting

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:

    - uses: actions/checkout@v4

    - name: Set up Python 3.9
      uses: actions/setup-python@v4
      with:
        python-version: "3.9"

    - name: Set up dependencies
      run: |
        python -m pip install --upgrade pip 
        python -m pip install flake8 flake8-rst-docstrings

# this linting considers also RST errors for Building the docs

    - name: Lint with flake8
      run : flake8 pysurfline