name: Flake8 Linting

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  lint:
    uses: giocaizzi/python-dev-actions/.github/workflows/linting.yml@main
    with:
      repo: ${{ github.repository }}