name: Upload Python Package

## https://github.com/pypa/gh-action-pypi-publish/issues/166
## pypi trusted publishing does not support reusable actions

on:
  release:
    types: [published]

jobs:
  pypi-publish:
    name: Upload release to PyPI
    runs-on: ubuntu-latest
    environment:
      name: pypi
      url: https://pypi.org/p/${{ github.event.repository.name }}
    permissions:
      id-token: write # IMPORTANT: this permission is mandatory for trusted publishing
    steps:
      - uses: pypa/gh-action-pypi-publish@release/v1
